import type { Metadata } from "next";

import Header from "@/components/header";
import { AuthProvider } from "@/providers/use-auth-provider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      
        <AuthProvider protection msg="Please sign in to access this page">
         
          {children}
         </AuthProvider>
      
    </main>
  );
}
